kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: iZjaGft697YHuphtv4U6OP/zWr/FsEZRAQ5JJboYi0U=
      - identity: {}
