---
version: '3.3'

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  comment_db:
    image: mongo:3.2
    volumes:
      - comment_db:/data/db
    networks:
      - back_net
  ui:
    env_file:
      - .env
    image: ${USERNAME}/ui:${SERVICE_VERSION}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    env_file:
      - .env
    image: ${USERNAME}/post:${SERVICE_VERSION}
    networks:
      - front_net
      - back_net
  comment:
    env_file:
      - .env
    image: ${USERNAME}/comment:${SERVICE_VERSION}
    networks:
      - front_net
      - back_net
  prometheus:
    env_file:
      - .env
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net
volumes:
  prometheus_data:
  post_db:
  comment_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24

